### PR TITLE
Update CHERI Concentrate compression listings

### PR DESCRIPTION
**Pull request by arichardson**
The listings now correspond to https://github.com/CTSRD-CHERI/cheri-cap-lib/commit/7d9fdce16a8ed8def1b5bd3f73109876179d6479

### CODE REVIEW

**Comment by PeterRugg** [comment]
Hmm, this includes my changes for the single cycle in-bounds check on CSetBounds, which is perhaps on the unstable side to include in the arch doc at the moment (evaluating it more thoroughly currently).
Also, do we think manual copies like this are the appropriate way forward, or would we want to pull it in automatically (or as a submodule) from cheri-cap-lib, as we do for Sail?

**Comment by arichardson** [comment]
> Hmm, this includes my changes for the single cycle in-bounds check on CSetBounds, which is perhaps on the unstable side to include in the arch doc at the moment (evaluating it more thoroughly currently). Also, do we think manual copies like this are the appropriate way forward, or would we want to pull it in automatically (or as a submodule) from cheri-cap-lib, as we do for Sail?

Oh good point, can you suggest a "stable" commit hash for this sync?

Longer-term, I agree that we should include the code instead of copying since it will get out-of-sync.

**Comment by PeterRugg** [comment]
Hmm, just before this one, so https://github.com/CTSRD-CHERI/cheri-cap-lib/commit/be80fbe51c0860394807980cf1823d229aeeaca7 is probably a good bet. Hopefully I'll be confident in the new check soon. I'm happy to have a shot at setting it up as per sail unless there's a reason to put off doing that?

**Comment by arichardson** [comment]
> Hmm, just before this one, so [CTSRD-CHERI/cheri-cap-lib@be80fbe](https://github.com/CTSRD-CHERI/cheri-cap-lib/commit/be80fbe51c0860394807980cf1823d229aeeaca7) is probably a good bet. Hopefully I'll be confident in the new check soon. I'm happy to have a shot at setting it up as per sail unless there's a reason to put off doing that?

Sure, I'll close this PR then.

**Pull request closed without merging**
